version: '3'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - my-postgres
      - redis

  my-postgres:
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  celery:
    build: .
    user: django-user
    command: ["celery", "-A", "thehomeworld", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis
  
  celerybeat:
    build: .
    user: django-user
    command: ["celery", "-A", "thehomeworld", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
      - my-postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}