# Generated by Django 5.0.8 on 2024-08-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=32, unique=True)),
                ('types', models.JSONField()),
                ('classes', models.JSONField()),
                ('subtypes', models.JSONField()),
                ('element', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('effect', models.CharField(null=True)),
                ('effect_raw', models.CharField(null=True)),
                ('rule', models.JSONField(null=True)),
                ('flavor', models.CharField(max_length=255, null=True)),
                ('cost_memory', models.IntegerField(null=True)),
                ('cost_reserve', models.IntegerField(null=True)),
                ('level', models.IntegerField(null=True)),
                ('power', models.IntegerField(null=True)),
                ('life', models.IntegerField(null=True)),
                ('durability', models.IntegerField(null=True)),
                ('speed', models.BooleanField(null=True)),
                ('legality', models.JSONField(null=True)),
                ('related_ids', models.JSONField(null=True)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('prefix', models.CharField(max_length=16)),
                ('language', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TcgPlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField()),
                ('productConditionID', models.IntegerField()),
                ('condition', models.CharField(max_length=255)),
                ('game', models.CharField(max_length=255)),
                ('isSupplemental', models.BooleanField()),
                ('lowPrice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('marketPrice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('number', models.CharField(max_length=16)),
                ('printing', models.CharField(max_length=32)),
                ('productName', models.CharField(max_length=255)),
                ('rarity', models.CharField(max_length=32)),
                ('sales', models.IntegerField()),
                ('set', models.CharField(max_length=128)),
                ('setAbbrv', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TcgPlayerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setNameId', models.IntegerField()),
                ('categoryId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cleanSetName', models.CharField(max_length=255)),
                ('urlName', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('releaseDate', models.DateTimeField(null=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=32, unique=True)),
                ('collector_number', models.CharField(max_length=16)),
                ('slug', models.CharField(max_length=255)),
                ('illustrator', models.CharField(max_length=128)),
                ('rarity', models.IntegerField()),
                ('effect', models.CharField(max_length=255, null=True)),
                ('flavor', models.CharField(max_length=255, null=True)),
                ('thema_grace_nonfoil', models.IntegerField()),
                ('thema_valor_nonfoil', models.IntegerField()),
                ('thema_charm_nonfoil', models.IntegerField()),
                ('thema_mystique_nonfoil', models.IntegerField()),
                ('thema_ferocity_nonfoil', models.IntegerField()),
                ('thema_grace_foil', models.IntegerField()),
                ('thema_valor_foil', models.IntegerField()),
                ('thema_charm_foil', models.IntegerField()),
                ('thema_mystique_foil', models.IntegerField()),
                ('thema_ferocity_foil', models.IntegerField()),
                ('thema_foil', models.IntegerField()),
                ('thema_nonfoil', models.IntegerField()),
                ('circulations', models.JSONField()),
                ('circulationTemplates', models.JSONField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardprice.indexcard')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardprice.indexset')),
            ],
        ),
    ]
