# Generated by Django 5.0.8 on 2024-08-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardprice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexedition',
            name='thema_charm_foil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='thema_charm_nonfoil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='thema_ferocity_foil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='thema_ferocity_nonfoil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='thema_foil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='thema_grace_foil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='thema_grace_nonfoil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='thema_mystique_foil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='thema_mystique_nonfoil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='thema_nonfoil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='thema_valor_foil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='thema_valor_nonfoil',
            field=models.IntegerField(null=True),
        ),
    ]
