# Generated by Django 5.0.8 on 2024-08-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardprice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcgplayerset',
            name='releaseDate',
            field=models.DateTimeField(null=True),
        ),
    ]
