# Generated by Django 5.0.8 on 2024-08-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardprice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcgplayercard',
            name='sales',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
