# Generated by Django 5.0.8 on 2024-08-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardprice', '0002_alter_indexedition_thema_charm_foil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexedition',
            name='effect',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='flavor',
            field=models.CharField(null=True),
        ),
    ]
