# Generated by Django 5.0.8 on 2024-08-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardprice', '0003_alter_indexedition_effect_alter_indexedition_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcard',
            name='effect',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='indexcard',
            name='effect_raw',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='indexcard',
            name='flavor',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='effect',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='indexedition',
            name='flavor',
            field=models.TextField(null=True),
        ),
    ]
